version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
    - ./data:/data/db
  meter:
    image: aygamesco/meter:latest
    ports:
    - 6565:6565
    environment:
      MONGO_URI: mongodb://localhost:27017/meter
